apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: ns-networking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
