# Service selector doesn't match pod labels.
apiVersion: v1
kind: Service
metadata:
  name: web-frontend-svc
  namespace: ns-networking
spec:
  selector:
    app: web-frontend-v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
